"""empty message

Revision ID: f38537d7b038
Revises: b87c48adca49
Create Date: 2024-11-06 20:11:59.675481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f38537d7b038'
down_revision = 'b87c48adca49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('person_class', sa.String(length=250), nullable=True),
    sa.Column('faccion', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planeta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('temp', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('vehiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('modelo')
    )
    op.drop_table('planetas')
    op.drop_table('vehiculos')
    op.drop_table('personajes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personajes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('person_class', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('faccion', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='personajes_pkey')
    )
    op.create_table('vehiculos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('modelo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='vehiculos_pkey'),
    sa.UniqueConstraint('modelo', name='vehiculos_modelo_key')
    )
    op.create_table('planetas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('temp', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='planetas_pkey'),
    sa.UniqueConstraint('name', name='planetas_name_key')
    )
    op.drop_table('vehiculo')
    op.drop_table('planeta')
    op.drop_table('personaje')
    # ### end Alembic commands ###
